# Generated by Django 3.1.6 on 2022-12-19 04:06

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.CharField(max_length=50, unique=True)),
                ('user_pw', models.CharField(max_length=20)),
                ('user_pw2', models.CharField(default='', max_length=20)),
                ('user_name', models.CharField(max_length=50)),
                ('email_addr', models.EmailField(max_length=128, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user_validate', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False, help_text='admin_info', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='account_active or is not disabled', verbose_name='active')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            managers=[
                ('object', user.models.UserManager()),
            ],
        ),
    ]
