# Generated by Django 3.1.6 on 2022-12-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('board', '0006_auto_20221221_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='like_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='like_boards', to='user.User'),
        ),
    ]
